import * as DuffelAPITypes from 'types'

export interface PaymentRequirements {
  /**
   *  The ISO 8601 datetime by which you must pay for this order.
   * At this time, if still unpaid, the reserved space on the flight(s)
   * will be released and you will have to create a new order.
   * This will be null only for orders where `awaiting_payment` is `false`.
   */
  paymentRequiredBy?: string | null
  /**
   *  The ISO 8601 datetime at which the price associated
   * with the order will no longer be guaranteed by the airline
   * and the order will need to be repriced before payment.
   * This can be null when there is no price guarantee.
   */
  priceGuaranteeExpiresAt?: string | null
  /**
   * Whether immediate payment is required or not
   */
  requiresInstantPayment: boolean
}

export namespace Offers {
  export interface DestinationOrOriginProp {
    /**
     * The airports associated to a city.
     * This will only be provided where the `type` is `city`.
     */
    airports?: DuffelAPITypes.Airport[]
    city?: DuffelAPITypes.City
    cityName?: string
    iataCityCode?: string
    iataCode: string
    iataCountryCode: string
    icaoCode?: string
    id: string
    latitude?: number
    longitude?: number
    name: string
    timeZone?: string
    type: DuffelAPITypes.PlaceType
  }

  export interface OfferRequestSlice {
    /**
     * The ISO 8601 date on which the passengers want to depart
     */
    departureDate: string
    /**
     * The city or airport the passengers want to travel to
     */
    destination: DestinationOrOriginProp | string
    /**
     * The city or airport the passengers want to depart from
     */
    origin: DestinationOrOriginProp | string
    originType: DuffelAPITypes.PlaceType
    destinationType: DuffelAPITypes.PlaceType
  }

  /**
   * The passengers who want to travel. A passenger will have only a type or an age.
   */
  export interface OfferRequestPassenger {
    /**
     * The age of the passenger on the `departure_date` of the final slice.
     */
    age?: number

    /**
     * The type of the passenger.
     */
    type?: 'adult'

    /**
     * The identifier for the passenger, unique within this Offer Request and across all Offer Requests.
     * This ID will be generated by Duffel unless you had optionally provided one.
     * Optionally providing one has been deprecated.
     */
    id: string
  }

  export interface OfferRequest {
    cabinClass?: DuffelAPITypes.CabinClass
    /**
     * The slices that make up this offer request.
     * One-way journeys can be expressed using one slice, whereas return trips will need two.
     * @link https://duffel.com/docs/api/overview/key-principles
     */
    slices: OfferRequestSlice[]
    cabinClass?: DuffelAPITypes.CabinClass
    createdAt: string
    id: string
    liveMode: boolean
    offers?: Omit<Offer, 'availableServices'>[]
    passengers: OfferRequestPassenger[]
  }

  export interface CreateOfferRequest {
    cabinClass: DuffelAPITypes.CabinClass
    passengers: Omit<OfferRequestPassenger, 'id'>[]
    slices: Omit<OfferRequestSlice, 'originType' | 'destinationType'>[]
  }

  export interface CreateOfferQueryParameters {
    /**
     * When set to `true`, the offer request resource returned will include all the offers returned by the airlines.
     * If set to `false`, the offer request resource won't include any offers.
     * To retrieve the associated `offers` later, use the [List Offers](https://duffel.com/docs/api/offers/get-offers) endpoint, specifying the `offer_request_id`.
     * You should use this option if you want to take advantage of the pagination, sorting and filtering that the [List Offers](https://duffel.com/docs/api/offers/get-offers) endpoint provides.
     */
    returnOffers: boolean
  }
}
