name: Release to NPM
on:
  push:
    branches:
      - main
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .tool-versions

      - name: Enable Corepack
        run: corepack enable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(corepack yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: corepack yarn install --immutable

      - name: Get version from package.json before release step
        id: initversion
        run: echo "version=$(npm run get-version --silent)" >> "$GITHUB_OUTPUT"

      - name: Build NPM package
        run: corepack yarn build

      - name: Release to NPM
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: duffel-bot
          GIT_AUTHOR_EMAIL: duffel-bot-read-write@duffel.com
          GIT_COMMITTER_NAME: duffel-bot
          GIT_COMMITTER_EMAIL: duffel-bot-read-write@duffel.com
        run: corepack yarn release

      - name: Get version from package.json after release step
        id: extractver
        run: echo "extractver=$(npm run get-version --silent)" >> "$GITHUB_OUTPUT"

      - name: Check if package versions are different
        run: |
          echo "Init Version - ${{ steps.initversion.outputs.version }}"
          echo "extract version - ${{ steps.extractver.outputs.extractver }}"
          echo "extract version - ${{ steps.initversion.outputs.version != steps.extractver.outputs.extractver }}"

      - name: Create Pull Request with updated package files
        id: cpr
        if: steps.initversion.outputs.version != steps.extractver.outputs.extractver
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'ci(release): ${{ steps.extractver.outputs.extractver }}'
          committer: duffel-bot <duffel-bot-read-write@duffel.com>
          author: duffel-bot <duffel-bot-read-write@duffel.com>
          title: 'ci(release): ${{ steps.extractver.outputs.extractver }}'
          body: 'Version bump in package.json and package-lock.json for release [${{ steps.extractver.outputs.extractver }}](https://github.com/${{github.repository}}/releases/tag/v${{ steps.extractver.outputs.extractver }})'
          branch: version-bump/${{ steps.extractver.outputs.extractver }}
          labels: |
            automated pr

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3.0.0
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
